name: Bump version

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: "Bump rule to increase the version"
        type: choice
        required: true
        default: "patch"
        options:
          - "major"
          - "minor"
          - "patch"
jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.bump-version.outputs.version }}
      branchname: ${{ steps.bump-version.outputs.branchname }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python - -y
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Bump Version
        id: bump-version
        run: |
          poetry version ${{ github.event.inputs.version_bump }}
          version = $(poetry version --short)
          echo "version=${version}" >> $GITHUB_OUTPUT
          echo "branchname=release-${version}" >> $GITHUB_OUTPUT
      - name: Commit Version Bump
        run: |
          git config --local user.email "mkah91@users.noreply.github.com"
          git config --local user.name "mkah91"
          git checkout -b ${{ steps.bump-version.outputs.branchname }}
          git add pyproject.toml
          git commit -m "Bump version: ${{ steps.bump-version.outputs.version }}"
          git push --set-upstream origin ${{ steps.bump-version.outputs.branchname }}
          git tag -a ${{ steps.bump-version.outputs.version }} -m "Release ${{ steps.bump-version.outputs.version }}"
          git push origin ${{ steps.bump-version.outputs.version }}
      - name: Create Pull Request
        run: |
          gh pr create \
          --base main \
          --head ${{ steps.bump-version.outputs.branchname }} \
          --title "Bump version to ${{ steps.bump-version.outputs.version }}" \
          --body "Created by GitHub Action"
